import React, { Component } from "react";

class Buttons extends Component {
  render() {
    return (
      <div className="buttons">
        <div className="numbers">
          <button
            data-val="9"
            value="9"
            id="nine"
            onClick={this.props.handleNumbers}
          >
            9
          </button>
          <button
            data-val="8"
            value="8"
            id="eight"
            onClick={this.props.handleNumbers}
          >
            8
          </button>
          <button
            data-val="7"
            value="7"
            id="seven"
            onClick={this.props.handleNumbers}
          >
            7
          </button>
          <button
            data-val="6"
            value="6"
            id="six"
            onClick={this.props.handleNumbers}
          >
            6
          </button>
          <button
            data-val="5"
            value="5"
            id="five"
            onClick={this.props.handleNumbers}
          >
            5
          </button>
          <button
            data-val="4"
            value="4"
            id="four"
            onClick={this.props.handleNumbers}
          >
            4
          </button>
          <button
            data-val="3"
            value="3"
            id="three"
            onClick={this.props.handleNumbers}
          >
            3
          </button>
          <button
            data-val="2"
            value="2"
            id="two"
            onClick={this.props.handleNumbers}
          >
            2
          </button>
          <button
            data-val="1"
            value="1"
            id="one"
            onClick={this.props.handleNumbers}
          >
            1
          </button>
          <button data-val="clear" id="clear" onClick={this.props.initialize}>
            C
          </button>
          <button
            data-val="."
            id="decimal"
            value="."
            onClick={this.props.handleDecimal}
          >
            .
          </button>
          <button
            data-val="0"
            href="0"
            value="0"
            id="zero"
            onClick={this.props.handleNumbers}
          >
            0
          </button>
        </div>
        <div className="operators">
          <button
            data-val="÷"
            id="divide"
            value="/"
            onClick={this.props.handleOperators}
          >
            ÷
          </button>
          <button
            data-val="x"
            id="multiply"
            value="x"
            onClick={this.props.handleOperators}
          >
            x
          </button>
          <button
            data-val="-"
            id="subtract"
            value="‑"
            onClick={this.props.handleOperators}
          >
            -
          </button>
          <button
            data-val="+"
            id="add"
            value="+"
            onClick={this.props.handleOperators}
          >
            +
          </button>
          <button
            data-val="="
            id="equals"
            value="="
            onClick={this.props.handleEvaluate}
          >
            =
          </button>
        </div>
      </div>
    );
  }
}
export default Buttons;
